apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-adapter-monitoring
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.wva.prometheus.serviceAccountName }}
    namespace: {{ .Values.wva.prometheus.monitoringNamespace }}
