apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    control-plane: controller-manager
    openshift.io/user-monitoring: "true"
  name: workload-variant-autoscaler-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      port: https
      scheme: https
      bearerTokenSecret:
        name: workload-variant-autoscaler-controller-manager-token-manual
        key: token
      tlsConfig:
        insecureSkipVerify: {{ if and .Values.wva.prometheus.tls (hasKey .Values.wva.prometheus.tls "insecureSkipVerify") }}{{ .Values.wva.prometheus.tls.insecureSkipVerify }}{{ else }}true{{ end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: workload-variant-autoscaler
      control-plane: controller-manager
