apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload-variant-autoscaler-metrics-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-variant-autoscaler-metrics-reader
subjects:
- kind: ServiceAccount
  name: workload-variant-autoscaler-controller-manager
  namespace: {{ .Release.Namespace }}