apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vllm-deployment-hpa
  namespace: {{ .Values.llmd.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "ms-%s-llm-d-modelservice-decode" .Values.wva.baseName }}
  # minReplicas: 0  # scale to zero - alpha feature
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # tune this value 
      policies:
      - type: Pods
        value: 10
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 0 # tune this value
      policies:
      - type: Pods
        value: 10
        periodSeconds: 15
  metrics:
  - type: External
    external:
      metric:
        name: inferno_desired_replicas
        selector:
          matchLabels:
            variant_name: {{ printf "ms-%s-llm-d-modelservice-decode" .Values.wva.baseName }}
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.targetAverageValue | quote }}
