{{- if .Values.wva.va.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-servicemonitor
  namespace: {{ .Values.wva.monitoringNamespace }}
  labels:
    llm-d.ai/model: {{ .Values.wva.modelName }}
spec:
  selector:
    matchLabels:
      llm-d.ai/model: {{ .Values.wva.modelName }}
  endpoints:
  - port: vllm
    path: /metrics
    interval: 15s
  namespaceSelector:
    any: true
{{- end }}