# This rule is not used by the project workload-variant-autoscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over llmd.llm-d.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: variantautoscaling-admin-role
rules:
- apiGroups:
  - llmd.llm-d.ai
  resources:
  - VariantAutoscalingss
  verbs:
  - '*'
- apiGroups:
  - llmd.llm-d.ai
  resources:
  - variantautoscalings/status
  verbs:
  - get
